src/models/base.py
from sqlalchemy.ext.declarative import as_declarative, declared_attr


@as_declarative()
class BaseClass:
    id: int
    __name__: str

    @declared_attr
    def __tablename__(self) -> str:
        return self.__name__.lower()

src/models/invoice_modes.py
from sqlalchemy import Integer, Column, ForeignKey

from src.models import BaseClass


class InvoiceModes(BaseClass):
    id = Column(Integer, primary_key=True, index=True)

    invoice_id = Column(Integer, ForeignKey('invoice.id'))
    mode_id = Column(Integer, ForeignKey('mode.id'))

    def __init__(self, invoice_id: int, mode_id: int):
        self.invoice_id = invoice_id
        self.mode_id = mode_id

    def __repr__(self):
        return f'Invoice(id={self.id}, invoice_id={self.invoice_id}, mode_id={self.mode_id})'

src/routes/admin.py
from flask import Blueprint, render_template, redirect, url_for, request

from src.logs import logger
from src.core.roles import ROLES
from src.core.roles import merged_login_role_required_decorator
from src.crud.user_operations import get_user_by_status, get_all_users
from src.crud.admin_operations import update_change_user_status
from src.crud.auth_operations import get_user_by_email, get_user_by_id
from src.crud.invoice_operations import update_invoice_completed_status, get_pending_invoices, get_split_user_invoices
from src.crud.discount_operations import get_current_discount_data, post_create_new_discount
from src.models import Discount
from src.path_structure import TEMPLATES_DIRECTORY_PATH


admin = Blueprint('admin', __name__, template_folder=TEMPLATES_DIRECTORY_PATH)


@admin.route('/', methods=['GET'])
@merged_login_role_required_decorator(role_value='admin')
def admin_index():
    try:
        admin_users = get_user_by_status(status='admin')
        print(admin_users)
        return render_template('admin_index.html',
                               admin_users=admin_users)
    except Exception as err:
        logger.logging.error(err)
        return redirect(url_for('index.main'))


@admin.route('/update-user-status', methods=['GET'])
@merged_login_role_required_decorator(role_value='admin')
def admin_update_user_status_get():
    try:
        return render_template('admin_status.html')
    except Exception as err:
        logger.logging.error(err)
        return redirect(url_for('admin.admin_index'))


@admin.route('/update-user-status', methods=['POST'])
@merged_login_role_required_decorator(role_value='admin')
def admin_update_user_status_post():
    try:
        targeted_user = get_user_by_email(email=request.form.get('user_email'))
        if targeted_user.name == request.form.get('user_name'):
            update_change_user_status(new_role='admin', user_id=targeted_user.id)
        else:
            logger.logging.info('wrong input data')
        return redirect(url_for('admin.admin_index'))
    except Exception as err:
        logger.logging.error(err)
        return redirect(url_for('admin.admin_index'))


@admin.route('/update-discount-status', methods=['GET'])
@merged_login_role_required_decorator(role_value='admin')
def admin_update_discount_status_get():
    try:
        current_discount = get_current_discount_data()
        return render_template('admin_discount.html',
                               current_discount=current_discount)
    except Exception as err:
        logger.logging.error(err)
        return redirect(url_for('admin.admin_index'))


@admin.route('/update-discount-status', methods=['POST'])
@merged_login_role_required_decorator(role_value='admin')
def admin_update_discount_status_post():
    try:
        new_discount = Discount(base_discount=int(request.form.get('base_discount')),
                                additional_discount=int(request.form.get('additional_discount')),
                                additional_discount_description=str(request.form.get('additional_discount_desc')))
        post_create_new_discount(new_discount_object=new_discount)
        return redirect(url_for('admin.admin_update_discount_status_get'))
    except Exception as err:
        logger.logging.error(err)
        return redirect(url_for('admin.admin_update_discount_status_get'))


@admin.route('/remove-additional-discount', methods=['GET'])
@merged_login_role_required_decorator(role_value='admin')
def admin_remove_additional_discount():
    try:
        current_discount = get_current_discount_data()
        new_discount = Discount(base_discount=current_discount.base_discount,
                                additional_discount=0,
                                additional_discount_description='-')
        post_create_new_discount(new_discount_object=new_discount)
        return redirect(url_for('admin.admin_update_discount_status_get'))
    except Exception as err:
        logger.logging.error(err)
        return redirect(url_for('admin.admin_update_discount_status_get'))


@admin.route('/list-users', methods=['GET'])
@merged_login_role_required_decorator(role_value='admin')
def admin_list_users():
    try:
        users = get_all_users()
        user_role_mapper = {value: key for key, value in ROLES.items()}
        return render_template('admin_users.html',
                               users=users,
                               role_mapper=user_role_mapper)
    except Exception as err:
        logger.logging.error(err)
        return redirect(url_for('admin.admin_update_discount_status_get'))


@admin.route('/user/<int:user_id>', methods=['GET'])
@merged_login_role_required_decorator(role_value='admin')
def admin_user_view(user_id: int):
    try:
        user = get_user_by_id(user_id=user_id)
        # reverse ROLES dictionary for presenting user roles in named string format
        user_role_mapper = {value: key for key, value in ROLES.items()}
        user_split_by_five_invoices = get_split_user_invoices(user_id=user_id, split_number=5)
        return render_template('user_profile.html',
                               user=user,
                               role_mapper=user_role_mapper,
                               user_invoices_first_part=user_split_by_five_invoices[0],
                               user_invoices_rest=user_split_by_five_invoices[1])
    except Exception as err:
        logger.logging.error(err)
        return redirect(url_for('admin.admin_list_users'))


@admin.route('/invoice-confirm', methods=['GET'])
@merged_login_role_required_decorator(role_value='admin')
def admin_confirm_invoice_get():
    try:
        pending_invoices = get_pending_invoices()
        return render_template('admin_invoices.html',
                               pending_invoices=pending_invoices)
    except Exception as err:
        logger.logging.error(err)
        return redirect(url_for('admin.admin_list_users'))


@admin.route('/invoice-confirm/<int:invoice_id>', methods=['GET'])
@merged_login_role_required_decorator(role_value='admin')
def admin_confirm_invoice_post(invoice_id: int):
    try:
        update_invoice_completed_status(invoice_id=invoice_id)
        return redirect(url_for('admin.admin_confirm_invoice_get'))
    except Exception as err:
        logger.logging.error(err)
        return redirect(url_for('admin.admin_list_users'))

src/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, make_response
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash

from src.logs import logger
from src.models import User
from src.crud import auth_operations
from src.core.roles import merged_login_role_required_decorator
from src.path_structure import TEMPLATES_DIRECTORY_PATH


auth = Blueprint('auth', __name__, template_folder=TEMPLATES_DIRECTORY_PATH)


@auth.route('/login', methods=['GET'])
def login():
    return render_template('login.html')


@auth.route('/login', methods=['POST'])
def login_post():
    try:
        email = request.form.get('email')
        password = request.form.get('password')
        remember = True if request.form.get('remember') else False

        user = auth_operations.get_user_by_email(email)
        logger.logging.info(user)

        if not user or not check_password_hash(user.password, password):
            raise ValueError('Wrong credentials input')

        login_user(user, remember=remember)
        return redirect(url_for('index.main'))

    except ValueError as err:
        logger.logging.error(err)
        return redirect(url_for('auth.login'))


@auth.route('/signup', methods=['GET'])
def signup():
    return render_template('signup.html')


@auth.route('/signup', methods=['POST'])
def signup_post():
    try:
        email = request.form.get('email')
        name = request.form.get('name')
        password = request.form.get('password')
        car_registration = request.form.get('car_registration')

        user = auth_operations.get_user_by_email(email)
        logger.logging.info(user)

        if user:
            raise ValueError('email already exists')

        new_user_object = User(
            name=name,
            email=email,
            password=generate_password_hash(password, method='sha256'),
            car_registration=car_registration
        )
        # add new user to the database
        auth_operations.post_create_new_user(new_user_object)

        return redirect(url_for('auth.login'))

    except ValueError as err:
        logger.logging.error(err)
        return redirect(url_for('auth.signup'))


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index.main'))


@auth.route('admin-test')
@merged_login_role_required_decorator(role_value='admin')
def admin_test():
    return make_response({'status': 200, 'role': current_user.role})

src/routes/mode.py
from flask import Blueprint, render_template, redirect, url_for, request

from src.logs import logger
from src.core.roles import merged_login_role_required_decorator
from src.models import Mode
from src.crud.mode_operations import post_create_new_mode, get_modes_by_active_status, update_change_mode_active_status
from src.path_structure import TEMPLATES_DIRECTORY_PATH


mode = Blueprint('mode', __name__, template_folder=TEMPLATES_DIRECTORY_PATH)


@mode.route('/create', methods=['GET'])
@merged_login_role_required_decorator(role_value='admin')
def mode_create_get():
    try:
        return render_template('mode_create.html')
    except Exception as err:
        logger.logging.error(err)
        return redirect(url_for('admin.admin_index'))


@mode.route('/create', methods=['POST'])
@merged_login_role_required_decorator(role_value='admin')
def mode_create_post():
    try:
        new_mode = Mode(description=request.form.get('mode_description'),
                        price=int(request.form.get('mode_price')))
        post_create_new_mode(new_mode)
        return redirect(url_for('mode.mode_create_get'))
    except Exception as err:
        logger.logging.error(err)
        return redirect(url_for('mode.mode_create_get'))


@mode.route('/active', methods=['GET'])
@merged_login_role_required_decorator(role_value='admin')
def mode_list_active():
    try:
        active_modes = get_modes_by_active_status(active_status=True)
        return render_template('mode_list.html',
                               modes=active_modes,
                               status_operation='Deactivate modes')
    except Exception as err:
        logger.logging.error(err)
        return redirect(url_for('admin.admin_index'))


@mode.route('/inactive', methods=['GET'])
@merged_login_role_required_decorator(role_value='admin')
def mode_list_inactive():
    try:
        inactive_modes = get_modes_by_active_status(active_status=False)
        return render_template('mode_list.html',
                               modes=inactive_modes,
                               status_operation='Activate modes')
    except Exception as err:
        logger.logging.error(err)
        return redirect(url_for('admin.admin_index'))


@mode.route('/change-status/<int:mode_id>/<int:status>', methods=['GET'])
@merged_login_role_required_decorator(role_value='admin')
def mode_change_status(mode_id: int, status: int):
    try:
        update_change_mode_active_status(new_status=bool(status), mode_id=mode_id)
        if status == 1:
            return redirect(url_for('mode.mode_list_inactive'))
        else:
            return redirect(url_for('mode.mode_list_active'))
    except Exception as err:
        logger.logging.error(err)
        return redirect(url_for('admin.admin_index'))

src/routes/user.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user

from src.logs import logger
from src.core.roles import ROLES
from src.crud.auth_operations import get_user_by_id
from src.crud.program_operations import post_mode_in_program, delete_mode_from_program
from src.crud.invoice_operations import post_create_new_invoice, get_split_user_invoices
from src.utility.user_program import get_user_selected_and_available_modes
from src.utility.invoice_calculation import calculate_program_invoice_price
from src.models import Invoice
from src.path_structure import TEMPLATES_DIRECTORY_PATH


user = Blueprint('user', __name__, template_folder=TEMPLATES_DIRECTORY_PATH)


@user.route('/', methods=['GET'])
@user.route('/profile', methods=['GET'])
@login_required
def user_profile():
    try:
        user_data = get_user_by_id(user_id=current_user.id)
        user_role_mapper = {value: key for key, value in ROLES.items()}
        user_split_by_five_invoices = get_split_user_invoices(user_id=current_user.id, split_number=5)
        return render_template('user_profile.html',
                               user=user_data,
                               role_mapper=user_role_mapper,
                               user_invoices_first_part=user_split_by_five_invoices[0],
                               user_invoices_rest=user_split_by_five_invoices[1])
    except Exception as err:
        logger.logging.error(err)
        return redirect(url_for('index.main'))


@user.route('/program', methods=['GET'])
@login_required
def user_program():
    try:
        # splits modes by selected status
        selected_unselected_modes = get_user_selected_and_available_modes(user_id=current_user.id)
        price_with_discount = calculate_program_invoice_price(user_id=current_user.id)
        return render_template('user_program.html',
                               selected_modes=selected_unselected_modes[0],
                               unselected_modes=selected_unselected_modes[1],
                               program_price=price_with_discount,
                               user_id=current_user.id)
    except Exception as err:
        logger.logging.error(err)
        return redirect(url_for('user.user_profile'))


@user.route('/program/add-mode/<int:user_id>/<int:mode_id>', methods=['GET'])
@login_required
def user_program_add_mode(user_id: int, mode_id: int):
    try:
        post_mode_in_program(mode_id=mode_id, user_id=user_id)
        return redirect(url_for('user.user_program'))
    except Exception as err:
        logger.logging.error(err)
        return redirect(url_for('user.user_program'))


@user.route('/program/remove-mode/<int:user_id>/<int:mode_id>', methods=['GET'])
@login_required
def user_program_remove_mode(mode_id: int, user_id: int):
    try:
        delete_mode_from_program(mode_id=mode_id, user_id=user_id)
        return redirect(url_for('user.user_program'))
    except Exception as err:
        logger.logging.error(err)
        return redirect(url_for('user.user_program'))


@user.route('/program/create-invoice', methods=['GET'])
@login_required
def user_create_invoice():
    try:
        discounted_price = calculate_program_invoice_price(user_id=current_user.id)
        # case when no modes are selected inside the washing program
        if discounted_price == 0.0:
            return redirect(url_for('user.user_program'))
        new_invoice = Invoice(price=discounted_price, user_id=current_user.id)
        post_create_new_invoice(user_id=current_user.id, new_invoice_object=new_invoice)
        return redirect(url_for('user.user_program'))
    except Exception as err:
        logger.logging.error(err)
        return redirect(url_for('user.user_program'))

src/templates/admin_discount.html
{% extends "base.html" %}

{% block content %}

<div style="padding: 2em">
    <div style="max-width: 1000px; margin: 0 auto">
        <div class="alert alert-danger" role="alert">
            <h1> [Admin access] Discount update options </h1>
        </div>
        <div class="alert alert-primary" role="alert">
            <h1> Discount </h1>
            Current discount values
        </div>
        <div>
            <ul class="list-group">
                <li class="list-group-item">
                    <b> Base Discount: </b> {{ current_discount.base_discount }}
                </li>
                <li class="list-group-item">
                    <b> Additional Discount: </b> {{ current_discount.additional_discount }}
                </li>
                <li class="list-group-item">
                    <b> Additional Discount Description: </b> {{ current_discount.additional_discount_description }}
                </li>
                <li class="list-group-item">
                    <b> Valid since: </b> {{ current_discount.valid_since }}
                </li>
            </ul>
        </div>
        <div style="margin-top: 2em">
            <div class="alert alert-danger" role="alert">
                <div>
                    <h1> Remove additional discount </h1>
                    Base discount value is not changed, just additional discount and description are removed.
                </div>
                <div style="margin-top: 1em">
                    <button class="alert alert-danger" type="button"
                            onclick="window.location.href='{{ url_for('admin.admin_remove_additional_discount') }}';">
                        Remove additional discount
                    </button>
                </div>
            </div>
        </div>
        <div>
            <form method="POST" action="/admin/update-discount-status">
                <div class="mb-3">
                    <label for="base_discount" class="form-label"> Base discount </label>
                    <input type="number"
                           placeholder="enter new base discount ... "
                           name="base_discount"
                           value="{{ current_discount.base_discount }}"
                           autofocus=""
                           class="form-control">
                </div>
                <div class="mb-3">
                    <label for="additional_discount" class="form-label"> Additional discount </label>
                    <input type="number"
                           placeholder="enter new additional discount ... "
                           name="additional_discount"
                           value="{{ current_discount.additional_discount }}"
                           autofocus=""
                           class="form-control">
                </div>
                <div class="mb-3">
                    <label for="additional_discount_desc" class="form-label"> Additional discount description </label>
                    <input type="text"
                           placeholder="enter new additional discount description ... "
                           name="additional_discount_desc"
                           value="{{ current_discount.additional_discount_description }}"
                           autofocus=""
                           class="form-control">
                </div>
                <button type="submit" class="btn btn-primary"> Update discount values </button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous"></script>
</head>

<body>
    <section>

        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
            <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href={{ url_for('index.main') }}> Home </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                User
                            </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href={{ url_for('user.user_profile') }}> Profile </a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href={{ url_for('user.user_program') }}> Program </a></li>
                                </ul>
                        </li>
                        {% if current_user.is_authenticated and current_user.role == 1 %}
                            <li class="nav-item">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" role="button"
                                       data-bs-toggle="dropdown" aria-expanded="false">
                                        Modes
                                    </a>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" href={{ url_for('mode.mode_list_active') }}> Active modes </a></li>
                                            <li><a class="dropdown-item" href={{ url_for('mode.mode_list_inactive') }}> Inactive modes </a></li>
                                            <li><hr class="dropdown-divider"></li>
                                            <li><a class="dropdown-item" href={{ url_for('mode.mode_create_get') }}> Create new mode </a></li>
                                        </ul>
                                </li>
                            </li>
                            <li class="nav-item">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" role="button"
                                       data-bs-toggle="dropdown" aria-expanded="false">
                                        Admin tools
                                    </a>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" href={{ url_for('admin.admin_index') }}> Admin users </a></li>
                                            <li><hr class="dropdown-divider"></li>
                                            <li><a class="dropdown-item" href={{ url_for('admin.admin_update_user_status_get') }}> Give admin status </a></li>
                                            <li><a class="dropdown-item" href={{ url_for('admin.admin_update_discount_status_get') }}> Update discount </a></li>
                                            <li><hr class="dropdown-divider"></li>
                                            <li><a class="dropdown-item" href={{ url_for('admin.admin_confirm_invoice_get') }}> Complete program </a></li>
                                            <li><a class="dropdown-item" href={{ url_for('admin.admin_list_users') }}> List users </a></li>
                                        </ul>
                                </li>
                            </li>
                        {% endif %}
                    </ul>
                    <div class="d-flex">
                        {% if not current_user.is_authenticated %}
                            <a class="dropdown-item" href={{ url_for('auth.login') }}>
                                <button class="btn btn-outline-success" type="submit" style="margin-left: 1em">Log in</button>
                            </a>
                            <a class="dropdown-item" href={{ url_for('auth.signup') }}>
                                <button class="btn btn-outline-primary" type="submit" style="margin-left: 1em">Sign up</button>
                            </a>
                        {% endif %}
                        {% if current_user.is_authenticated %}
                            <a class="dropdown-item" href={{ url_for('auth.logout') }}>
                                <button class="btn btn-outline-danger" type="submit" style="margin-left: 1em">Log out</button>
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>

        <div>
            <div>
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

src/templates/user_program.html
{% extends "base.html" %}

{% block content %}

<div style="padding: 2em">
    <div style="max-width: 1000px; margin: 0 auto">
        <div>
            <div class="alert alert-primary" role="alert">
                <h1> User program </h1>
                Create your personal washing program by selecting available washing modes
            </div>
            <div class="alert alert-primary" role="alert">
                <h1> Available modes </h1>
                List of available washing modes that are not part of your program
            </div>
            <div class="card card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col"> </th>
                            <th scope="col"> Description </th>
                            <th scope="col"> Price </th>
                            <th scope="col"> Add mode to program </th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        {% for mode in unselected_modes %}
                            <tr>
                                <th scope="row"> - </th>
                                <td> {{ mode.description }} </td>
                                <td> {{ mode.price }} </td>
                                <td>
                                    <button class="btn btn-success" type="button"
                                            onclick="window.location.href='{{ url_for('user.user_program_add_mode',
                                                                              mode_id=mode.id, user_id=user_id) }}';">
                                        Add mode to program
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div style="margin-top: 2em">
            <div class="alert alert-primary" role="alert">
                <h1> Selected Modes </h1>
                Current program content.
            </div>
            <div class="card card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col"> </th>
                            <th scope="col"> Description </th>
                            <th scope="col"> Price </th>
                            <th scope="col"> Remove mode from program </th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        {% for mode in selected_modes %}
                            <tr>
                                <th scope="row"> - </th>
                                <td> {{ mode.description }} </td>
                                <td> {{ mode.price }} </td>
                                <td>
                                    <button class="btn btn-danger" type="button"
                                            onclick="window.location.href='{{ url_for('user.user_program_remove_mode',
                                                                              mode_id=mode.id, user_id=user_id) }}';">
                                        Remove mode from program
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div style="margin-top: 2em">
            <div class="alert alert-danger" role="alert">
                <div>
                    <h1> Program order confirmation </h1>
                    <h3> Current program price: {{ program_price }} </h3>
                </div>
                <div style="margin-top: 1em">
                    {% if program_price != 0.0 %}
                        <button class="alert alert-danger" type="button"
                                onclick="window.location.href='{{ url_for('user.user_create_invoice') }}';">
                            Order program
                        </button>
                    {% endif %}
                    {% if program_price == 0.0 %}
                        <button class="alert alert-danger" type="button" disabled
                                onclick="window.location.href='{{ url_for('user.user_create_invoice') }}';">
                            Order program
                        </button>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}